"""Provider-specific integrations for Module 5."""

from .anthropic_tools import (
    MAX_ANTHROPIC_OUTPUT_TOKENS,
    MAX_ANTHROPIC_REQUESTS,
    MAX_ANTHROPIC_TOOL_CALLS,
    AnthropicToolLoopBudgetError,
    AnthropicToolUse,
    AnthropicToolUseError,
    AnthropicToolUseResult,
    anthropic_tools,
    execute_anthropic_tool_use,
    normalize_tool_use_block,
    run_anthropic_tool_use,
    to_anthropic_tool,
)
from .openai_tools import (
    MAX_OPENAI_REQUESTS,
    MAX_OPENAI_TOOL_CALLS,
    OpenAIFunctionCallingResult,
    OpenAIToolCall,
    OpenAIToolCallError,
    OpenAIToolLoopBudgetError,
    chat_tools,
    execute_openai_tool_call,
    normalize_chat_tool_call,
    normalize_response_tool_call,
    response_tools,
    run_openai_function_calling,
    to_openai_chat_tool,
    to_openai_response_tool,
)

__all__ = [
    "MAX_ANTHROPIC_OUTPUT_TOKENS",
    "MAX_ANTHROPIC_REQUESTS",
    "MAX_ANTHROPIC_TOOL_CALLS",
    "AnthropicToolLoopBudgetError",
    "AnthropicToolUse",
    "AnthropicToolUseError",
    "AnthropicToolUseResult",
    "anthropic_tools",
    "execute_anthropic_tool_use",
    "normalize_tool_use_block",
    "run_anthropic_tool_use",
    "to_anthropic_tool",
    "MAX_OPENAI_REQUESTS",
    "MAX_OPENAI_TOOL_CALLS",
    "OpenAIFunctionCallingResult",
    "OpenAIToolCall",
    "OpenAIToolCallError",
    "OpenAIToolLoopBudgetError",
    "chat_tools",
    "execute_openai_tool_call",
    "normalize_chat_tool_call",
    "normalize_response_tool_call",
    "response_tools",
    "run_openai_function_calling",
    "to_openai_chat_tool",
    "to_openai_response_tool",
]
